language: go
sudo: false
go:
  - tip
install:
  - go get -u golang.org/x/lint/golint
  - go get -d -t -v ./...
  - go build -v ./...
script:
  - go vet ./...
  - $HOME/gopath/bin/golint .
  - go test -v ./...
